[server]
maxMessageSize = 500
maxUploadSize = 500

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0369A1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
